<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>ClientStatusAlert_AtRisk</fullName>
        <description>After &apos;(R) Engagement Status&apos; for a client is deemed as an &apos;At Risk&apos; account</description>
        <protected>false</protected>
        <recipients>
            <recipient>jwinn@royall.com.abc</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>sdascoli@royall.com.abc</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Workflow_Email_Alert_Templates/Client_Alert_At_Risk</template>
    </alerts>
    <alerts>
        <fullName>ClientStatusAlert_Committed</fullName>
        <description>Alert client status is marked as committed.</description>
        <protected>false</protected>
        <recipients>
            <recipient>jwinn@royall.com.abc</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>sdascoli@royall.com.abc</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Workflow_Email_Alert_Templates/Client_Alert_Committed</template>
    </alerts>
    <alerts>
        <fullName>ClientStatusAlert_Lost</fullName>
        <description>Alert client status is marked as lost.</description>
        <protected>false</protected>
        <recipients>
            <recipient>jwinn@royall.com.abc</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>sdascoli@royall.com.abc</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Workflow_Email_Alert_Templates/Client_Alert_Lost</template>
    </alerts>
    <alerts>
        <fullName>ClientStatusAlert_Secured</fullName>
        <description>Alert client status is marked as secured.</description>
        <protected>false</protected>
        <recipients>
            <recipient>jwinn@royall.com.abc</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>sdascoli@royall.com.abc</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Workflow_Email_Alert_Templates/Client_Alert_Secured</template>
    </alerts>
    <alerts>
        <fullName>Client_Alert_New_RC</fullName>
        <ccEmails>newclientnotification@royall.com.abc</ccEmails>
        <description>Client Alert - New (RC)</description>
        <protected>false</protected>
        <recipients>
            <recipient>sdascoli@royall.com.abc</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Workflow_Email_Alert_Templates/Client_Alert_New_RC</template>
    </alerts>
    <fieldUpdates>
        <fullName>FY2010</fullName>
        <field>FY_Date__c</field>
        <formula>DATE(2010,06,30)</formula>
        <name>FY2010</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>FY2011</fullName>
        <field>FY_Date__c</field>
        <formula>DATE(2011,06,30)</formula>
        <name>FY2011</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>FY2012</fullName>
        <field>FY_Date__c</field>
        <formula>DATE (2012,06,30)</formula>
        <name>FY2012</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>FY2013</fullName>
        <field>FY_Date__c</field>
        <formula>DATE(2013,06,30)</formula>
        <name>FY2013</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>FY2014</fullName>
        <field>FY_Date__c</field>
        <formula>DATE(2014,06,30)</formula>
        <name>FY2014</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <rules>
        <fullName>Client Status Alert -- At Risk</fullName>
        <actions>
            <name>ClientStatusAlert_AtRisk</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.Client_Status_New__c</field>
            <operation>equals</operation>
            <value>At Risk</value>
        </criteriaItems>
        <description>Client status is marked at risk.</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Client Status Alert -- Committed</fullName>
        <actions>
            <name>ClientStatusAlert_Committed</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.Client_Status_New__c</field>
            <operation>equals</operation>
            <value>Committed</value>
        </criteriaItems>
        <description>Client status is marked as committed.</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Client Status Alert -- Lost</fullName>
        <actions>
            <name>ClientStatusAlert_Lost</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.Client_Status_New__c</field>
            <operation>equals</operation>
            <value>Lost</value>
        </criteriaItems>
        <description>Client status is marked as lost.</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Client Status Alert -- Secured</fullName>
        <actions>
            <name>ClientStatusAlert_Secured</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.Client_Status_New__c</field>
            <operation>equals</operation>
            <value>Secured</value>
        </criteriaItems>
        <criteriaItems>
            <field>Program_Package__c.Name</field>
            <operation>notContain</operation>
            <value>Miscellaneous Revenue Adjustment</value>
        </criteriaItems>
        <description>Client status is marked as secured.</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>FY2010</fullName>
        <actions>
            <name>FY2010</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.Fiscal_Year__c</field>
            <operation>equals</operation>
            <value>2010</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>FY2011</fullName>
        <actions>
            <name>FY2011</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.Fiscal_Year__c</field>
            <operation>equals</operation>
            <value>2011</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>FY2012</fullName>
        <actions>
            <name>FY2012</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.Fiscal_Year__c</field>
            <operation>equals</operation>
            <value>2012</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>FY2013</fullName>
        <actions>
            <name>FY2013</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.Fiscal_Year__c</field>
            <operation>equals</operation>
            <value>2013</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>FY2014</fullName>
        <actions>
            <name>FY2014</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.Fiscal_Year__c</field>
            <operation>equals</operation>
            <value>2014</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>New Client %28RC%29</fullName>
        <actions>
            <name>Client_Alert_New_RC</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Program_Package__c.R_Account_Status__c</field>
            <operation>equals</operation>
            <value>New Client</value>
        </criteriaItems>
        <description>Initiates workflow when there&apos;s a new Royall &amp; Company client</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
